name: Aprendiendo Github Actions
run-name: Aprendiendo el beta
on: [push]
jobs:
    hola-mundo:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Definir variable
            run: echo "USERNAME=${{ github.actor}}" >> $GITHUB_ENV
          - name: Correr script
            run: node main.js