name: Saludo usando variables y secretos
run-name: ¡Estoy aprendiendo a usar Variables!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Hoy es ${{env.DIA_DE_SEMANA}}"
        env:
          NOMBRE: Nelson
  saludos-secretos:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo secreto
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Tu secreto es ${{secrets.SECRETO_PAPA}}"
